#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

STACK_NAME="dex-dev-registry-stack"

echo "Loading parameters from parameters.json..."
PROJECT_NAME=$(jq -r '.ProjectName' parameters.json)
ENVIRONMENT=$(jq -r '.Environment' parameters.json)

# Check if stack exists
echo "Checking for existing infrastructure..."
STACK_STATUS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].StackStatus' \
  --output text 2>/dev/null || echo "DOES_NOT_EXIST")

if [[ "$STACK_STATUS" == "CREATE_COMPLETE" || "$STACK_STATUS" == "UPDATE_COMPLETE" || "$STACK_STATUS" == "UPDATE_ROLLBACK_COMPLETE" ]]; then
  echo "✓ Found existing infrastructure (Status: $STACK_STATUS)"
  echo "  Stack: $STACK_NAME"

  # Check tags
  TAGS=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query 'Stacks[0].Tags[?Key==`Purpose`].Value' \
    --output text 2>/dev/null || echo "")

  if [[ "$TAGS" == "DexRegistry" ]]; then
    echo "  Tags: ✓ DexRegistry"
  fi

  echo ""
  echo "Updating CloudFormation stack..."
fi

if [[ "$STACK_STATUS" != "DOES_NOT_EXIST" ]]; then
  echo "Deploying/updating CloudFormation stack: $STACK_NAME"
else
  echo "✗ No existing infrastructure found"
  echo ""
  echo "Deploying CloudFormation stack: $STACK_NAME"
fi

echo ""

# Start deployment in background and capture output
aws cloudformation deploy \
  --stack-name "$STACK_NAME" \
  --template-file cloudformation.yaml \
  --parameter-overrides \
    ProjectName="$PROJECT_NAME" \
    Environment="$ENVIRONMENT" \
  --capabilities CAPABILITY_IAM \
  --no-fail-on-empty-changeset \
  --tags \
    Project="$PROJECT_NAME" \
    Environment="$ENVIRONMENT" \
    ManagedBy=CloudFormation \
    Purpose=DexRegistry &

DEPLOY_PID=$!

# Poll for stack events while deployment is running
echo "Monitoring stack events:"
LAST_EVENT_TIME=""
while kill -0 $DEPLOY_PID 2>/dev/null; do
  EVENTS=$(aws cloudformation describe-stack-events \
    --stack-name "$STACK_NAME" \
    --query 'StackEvents[?Timestamp>`'"$LAST_EVENT_TIME"'`].[Timestamp,ResourceStatus,ResourceType,LogicalResourceId]' \
    --output text 2>/dev/null | sort)

  if [[ -n "$EVENTS" ]]; then
    while IFS=$'\t' read -r timestamp status type resource; do
      if [[ -n "$timestamp" && "$timestamp" != "$LAST_EVENT_TIME" ]]; then
        printf "  [%s] %-20s %-30s %s\n" \
          "$(date -j -f "%Y-%m-%dT%H:%M:%S" "${timestamp%.*}" "+%H:%M:%S" 2>/dev/null || echo "$timestamp")" \
          "$status" \
          "$type" \
          "$resource"
        LAST_EVENT_TIME="$timestamp"
      fi
    done <<< "$EVENTS"
  fi
  sleep 2
done

# Wait for background process and get exit code
wait $DEPLOY_PID
DEPLOY_EXIT=$?

if [ $DEPLOY_EXIT -eq 0 ]; then
  echo ""
  echo "✓ Infrastructure deployment/update complete!"
else
  echo ""
  echo "✗ Infrastructure deployment failed (exit code: $DEPLOY_EXIT)"
  exit $DEPLOY_EXIT
fi

echo ""
echo "Retrieving stack outputs..."
BUCKET_NAME=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`BucketName`].OutputValue' \
  --output text)

REGISTRY_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`RegistryURL`].OutputValue' \
  --output text)

S3_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --query 'Stacks[0].Outputs[?OutputKey==`S3URL`].OutputValue' \
  --output text)

echo "Writing configuration to config.sh..."
cat > config.sh <<EOF
# Generated by infrastructure/deploy.sh
export BUCKET_NAME="$BUCKET_NAME"
export REGISTRY_URL="$REGISTRY_URL"
export S3_URL="$S3_URL"
EOF

echo ""
echo "✓ Configuration ready!"
echo "  Bucket: $BUCKET_NAME"
echo "  Registry URL: $REGISTRY_URL"
echo "  S3 URL: $S3_URL"
